global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: master
    static_configs:
      - targets: ["master:8000"]  # must match MASTER_HTTP_PORT in .env

  - job_name: workers
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.json
        refresh_interval: 10s
